services:
  jenkins:
    image: kcandidate/jenkins-casc:2025.03.11.2245-07f2a3d
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - /mnt/nfs/jenkins_nfs/:/var/jenkins_home/
    restart: always
