services:
  jenkins:
    image: kcandidate/jenkins-casc:2025.01.15.1752-a45e37c
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - /mnt/nfs/jenkins_nfs/:/var/jenkins_home/
    restart: always
