services:
  jenkins:
    image: kcandidate/jenkins-casc:2025.03.12.0122-4fea103
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - /mnt/nfs/jenkins_nfs/:/var/jenkins_home/
    restart: always
